# Generated by Django 5.2.9 on 2025-12-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'В работе'), ('completed', 'Завершен'), ('deferred', 'Отложен')], max_length=50)),
                ('responsible', models.CharField(max_length=255)),
            ],
        ),
    ]
