# Generated by Django 5.2.9 on 2025-12-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profi_way', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
