# Generated by Django 5.2.9 on 2025-12-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QAItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortquery', models.CharField(max_length=255)),
                ('fullquery', models.TextField()),
                ('appsname', models.CharField(choices=[('common_core', 'Общее ядро'), ('house_hold', 'Дом и учет'), ('profi_way', 'ML и разработка'), ('trading_investments', 'Трейдинг и инвестиции'), ('consulting', 'Консультирование')], default='common_core', max_length=25)),
                ('querykind', models.CharField(choices=[('query', 'Вопрос'), ('task', 'Задача')], default='query', max_length=50)),
                ('is_urgent', models.BooleanField(default=False)),
                ('source', models.CharField(max_length=255)),
                ('asktime', models.DateField()),
                ('resolvetime', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'В работе'), ('resolved', 'Решен'), ('deferred', 'Отложен')], default='in_progress', max_length=50)),
                ('resansways', models.TextField()),
                ('resansfact', models.TextField()),
                ('coment', models.CharField(max_length=255)),
            ],
        ),
    ]
