# Generated by Django 5.2.9 on 2026-02-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_core', '0002_alter_qaitem_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_num', models.IntegerField()),
                ('count_org', models.CharField(max_length=150)),
                ('count_type', models.CharField(choices=[('payment', 'расчетный'), ('card', 'дебетовая карта'), ('broker', 'брокерский'), ('invest', 'инвестиционный'), ('credit', 'кредитный')])),
                ('current_sum', models.DecimalField(decimal_places=2, max_digits=15)),
                ('open_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
