# Generated by Django 5.2.9 on 2026-02-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_core', '0003_counts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counts',
            old_name='count_num',
            new_name='account_num',
        ),
        migrations.RenameField(
            model_name='counts',
            old_name='open_date',
            new_name='account_opendate',
        ),
        migrations.RenameField(
            model_name='counts',
            old_name='current_sum',
            new_name='account_sum',
        ),
        migrations.RemoveField(
            model_name='counts',
            name='count_org',
        ),
        migrations.RemoveField(
            model_name='counts',
            name='count_type',
        ),
        migrations.AddField(
            model_name='counts',
            name='account_country',
            field=models.CharField(default='РФ', max_length=150),
        ),
        migrations.AddField(
            model_name='counts',
            name='account_finorg',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='counts',
            name='account_owner',
            field=models.CharField(choices=[('individual', 'Физическое лицо'), ('legal_entity', 'Юридическое лицо')], default='individual'),
        ),
        migrations.AddField(
            model_name='counts',
            name='account_type',
            field=models.CharField(choices=[('payment', 'расчетный'), ('card', 'дебетовая карта'), ('broker', 'брокерский'), ('invest', 'инвестиционный'), ('credit', 'кредитный')], default='card'),
        ),
    ]
