# Generated by Django 5.2.9 on 2026-02-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_core', '0004_rename_count_num_counts_account_num_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=250)),
                ('org_type', models.CharField(choices=[('bank', 'банк'), ('broker', 'брокер'), ('dealer', 'дилер'), ('finteh', 'финтех'), ('stockmarket', 'биржа'), ('cryptomarket', 'криптобиржа'), ('forex', 'форекс'), ('realestate', 'недвижимость'), ('market', 'торговая сеть')], default='bank')),
                ('org_legal', models.CharField(default='РФ', max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='counts',
            name='account_currency',
            field=models.CharField(choices=[('RUR', 'руб'), ('USD', 'долл сша'), ('EUR', 'евро'), ('USDT', 'крипто долл')], default='RUR'),
        ),
        migrations.AddField(
            model_name='counts',
            name='account_curtype',
            field=models.CharField(choices=[('fiat', 'фиат'), ('cripto', 'крипто'), ('stocks', 'акции'), ('bonds', 'облигации'), ('objects', 'объекты')], default='фиат'),
        ),
        migrations.RemoveField(
            model_name='counts',
            name='account_finorg',
        ),
        migrations.AddField(
            model_name='counts',
            name='account_finorg',
            field=models.ManyToManyField(blank=True, to='common_core.organizations'),
        ),
    ]
