# Generated by Django 5.2.9 on 2026-02-05 13:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_core', '0005_organizations_counts_account_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counts',
            name='account_curtype',
            field=models.CharField(choices=[('fiat', 'фиат'), ('cripto', 'крипто'), ('stocks', 'акции'), ('bonds', 'облигации'), ('objects', 'объекты')], default='fiat'),
        ),
        migrations.AlterField(
            model_name='counts',
            name='account_opendate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='org_type',
            field=models.CharField(choices=[('bank', 'банк'), ('broker', 'брокер'), ('dealer', 'дилер'), ('fxdealer', 'форекс-дилер'), ('fond', 'фонд'), ('ratingagency', 'РА'), ('insurance', 'страховая компания'), ('creditbureau', 'кредитное бюро'), ('finteh', 'финтех'), ('stockmarket', 'биржа'), ('cryptomarket', 'криптобиржа'), ('forex', 'форекс'), ('realestate', 'недвижимость'), ('market', 'торговая сеть'), ('medical', 'медучреждение')], default='bank'),
        ),
    ]
