# Generated by Django 5.2.9 on 2026-02-05 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_core', '0006_alter_counts_account_curtype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counts',
            name='account_finorg',
        ),
        migrations.AlterField(
            model_name='counts',
            name='account_type',
            field=models.CharField(choices=[('payment', 'расчетный'), ('card', 'дебетовая карта'), ('broker', 'брокерский'), ('invest', 'инвестиционный'), ('credit', 'кредитный'), ('ndd', 'not dealing desk'), ('direct', 'direct')], default='card'),
        ),
        migrations.AddField(
            model_name='counts',
            name='account_finorg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='common_core.organizations'),
        ),
    ]
