# Generated by Django 5.2.9 on 2026-02-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_core', '0007_remove_counts_account_finorg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counts',
            name='owner_name',
            field=models.CharField(choices=[('S', 'СБ'), ('I', 'ИБ'), ('V', 'ВБ'), ('T', 'ТК')], default='S', max_length=5),
        ),
    ]
