# Generated by Django 5.2.9 on 2026-02-05 16:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_core', '0008_counts_owner_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=200)),
                ('tag_name', models.CharField(blank=True, max_length=50, null=True)),
                ('kind_of_book', models.CharField(blank=True, max_length=50, null=True)),
                ('author', models.CharField(max_length=100)),
                ('pages', models.PositiveIntegerField()),
                ('subject', models.CharField(max_length=100, null=True)),
                ('publ_seria', models.CharField(blank=True, max_length=100, null=True)),
                ('is_q_and_exc', models.BooleanField(default=False)),
                ('is_answers', models.BooleanField(default=False)),
                ('timestart', models.DateField(blank=True, null=True)),
                ('timefin_plan', models.DateField(blank=True, null=True)),
                ('timefin_fact', models.DateField(blank=True, null=True)),
                ('rating', models.IntegerField(null=True)),
                ('basic_thoughts', models.TextField(blank=True, null=True)),
                ('publ_year', models.IntegerField()),
                ('publ_house', models.CharField(max_length=100, null=True)),
                ('publ_city', models.CharField(blank=True, max_length=100, null=True)),
                ('coment', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'ordering': ['book_name'],
            },
        ),
        migrations.CreateModel(
            name='MedCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medcatname', models.CharField(max_length=150)),
                ('medapp', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_date', models.DateField(auto_now_add=True)),
                ('note_type', models.CharField(choices=[('note', 'заметка'), ('thought', 'размышление'), ('task', 'задача')], default='task')),
                ('note_category', models.CharField(choices=[('common_core', 'справочники'), ('house_hold', 'дом и учет'), ('consulting', 'консультирование'), ('profi_way', 'разработка и MLOps'), ('ttrading_investments', 'трейдинг/инвестирование')], default='common_core')),
                ('note_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameplan', models.CharField(default='План', max_length=150)),
                ('plan_type', models.CharField(choices=[('shortprd', 'краткосрочный'), ('mediumprd', 'среднесрочный'), ('longprd', 'долгосрочный')])),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('finish_date', models.DateField(default=django.utils.timezone.now)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='counts',
            name='is_fnsknown',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medname', models.CharField()),
                ('medcoment', models.CharField(max_length=250, null=True)),
                ('is_nesessary', models.BooleanField(default=False)),
                ('medcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meds', to='common_core.medcategory')),
            ],
        ),
    ]
