# Generated by Django 5.2.9 on 2026-02-06 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_core', '0009_books_medcategory_notes_plans_counts_is_fnsknown_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counts',
            name='account_coment',
            field=models.CharField(default='Привязана карта: ****', max_length=150),
        ),
        migrations.AddField(
            model_name='counts',
            name='is_cardlinked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='counts',
            name='account_type',
            field=models.CharField(choices=[('payment', 'расчетный'), ('card', 'дебетовая карта'), ('savings ', 'накопительный'), ('deposit', 'вклад/депозит'), ('broker', 'брокерский'), ('invest', 'инвестиционный'), ('depo', 'депозитарный'), ('credit', 'кредитный'), ('ndd', 'not dealing desk'), ('direct', 'direct')], default='card'),
        ),
    ]
