# Generated by Django 5.2.9 on 2026-02-06 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_core', '0010_counts_account_coment_counts_is_cardlinked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counts',
            name='account_coment',
            field=models.CharField(default='Привязана карта: ****', max_length=150, null=True),
        ),
    ]
