# Generated by Django 5.2.9 on 2026-02-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_core', '0011_alter_counts_account_coment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counts',
            name='account_coment',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
