# Generated by Django 5.2.9 on 2026-02-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_core', '0013_alter_organizations_org_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizations',
            name='org_type',
            field=models.CharField(choices=[('bank', 'банк'), ('broker', 'брокер'), ('dealer', 'дилер'), ('fxdealer', 'форекс-дилер'), ('fond', 'фонд'), ('ratingagency', 'РА'), ('insurance', 'страховая компания'), ('creditbureau', 'кредитное бюро'), ('finteh', 'финтех'), ('stockmarket', 'биржа'), ('cryptomarket', 'криптобиржа'), ('forex', 'форекс'), ('realestate', 'недвижимость'), ('market', 'торговая сеть'), ('medical', 'медучреждение')], default='bank'),
        ),
    ]
