# Generated by Django 5.2.9 on 2026-02-07 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_core', '0014_alter_organizations_org_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catname', models.CharField(max_length=150)),
                ('catbuhtype', models.CharField(choices=[('income', 'доход'), ('expense', 'расход')], default='income')),
                ('catusertype', models.CharField(choices=[('profit', 'поступления'), ('payments', 'выплаты'), ('products', 'товары'), ('services', 'услуги')], default='')),
                ('catstatus', models.CharField(choices=[('constant', 'постоянный'), ('temporary', 'временный'), ('discret', 'дискретный')], default='')),
                ('catperiod', models.CharField(choices=[('daily', 'ежедневный'), ('weekly', 'еженедельный'), ('monthly', 'ежемесячный'), ('quartly', 'ежеквартальный'), ('annually', 'ежегодный')], default='')),
            ],
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='medcategory',
        ),
        migrations.AddField(
            model_name='organizations',
            name='org_url',
            field=models.URLField(null=True),
        ),
        migrations.CreateModel(
            name='SubCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodname', models.CharField()),
                ('prodbasket', models.CharField(choices=[])),
                ('prodcoment', models.CharField(max_length=250, null=True)),
                ('is_nesessary', models.BooleanField(default=False)),
                ('prodcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prods', to='common_core.categories')),
            ],
        ),
        migrations.DeleteModel(
            name='MedCategory',
        ),
        migrations.DeleteModel(
            name='Medicine',
        ),
    ]
