# Generated by Django 5.2.9 on 2026-02-07 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_core', '0015_categories_remove_medicine_medcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategories',
            name='prodbasket',
            field=models.CharField(choices=[('base', 'базовый'), ('standart', 'стандартный'), ('upstandart', 'расширенный'), ('premium', 'премиальный')], default='base'),
        ),
    ]
