# Generated by Django 5.2.9 on 2026-02-07 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_core', '0016_alter_subcategories_prodbasket'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeeperApps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appname', models.CharField(max_length=50)),
                ('applabel', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=150)),
                ('keeperapps', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apps', to='common_core.keeperapps')),
            ],
        ),
        migrations.AlterField(
            model_name='qaitem',
            name='appsname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projectapp', to='common_core.keeperapps'),
        ),
    ]
