# Generated by Django 5.2.9 on 2026-02-07 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_core', '0017_keeperapps_actions_alter_qaitem_appsname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qaitem',
            name='appsname',
            field=models.CharField(choices=[('common_core', 'Общее ядро'), ('house_hold', 'Дом и учет'), ('profi_way', 'ML и разработка'), ('trading_investments', 'Трейдинг и инвестиции'), ('consulting', 'Консультирование')], default='common_core'),
        ),
    ]
