# Generated by Django 5.2.9 on 2026-02-07 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_core', '0018_alter_qaitem_appsname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qaitem',
            name='appsname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projectapp', to='common_core.keeperapps'),
        ),
    ]
