# Generated by Django 5.2.9 on 2026-02-07 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_core', '0019_alter_qaitem_appsname'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortquery', models.CharField(max_length=255)),
                ('fullquery', models.TextField()),
                ('is_urgent', models.BooleanField(default=False)),
                ('source', models.CharField(max_length=255)),
                ('asktime', models.DateTimeField(auto_now_add=True)),
                ('resolvetime', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'В работе'), ('resolved', 'Решен'), ('deferred', 'Отложен')], default='in_progress', max_length=50)),
                ('resansways', models.TextField()),
                ('resansfact', models.TextField()),
                ('coment', models.CharField(max_length=255)),
                ('appsname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projectapp', to='common_core.keeperapps')),
            ],
        ),
        migrations.DeleteModel(
            name='QAItem',
        ),
    ]
