# Generated by Django 5.2.9 on 2026-02-07 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_core', '0020_queryanswers_delete_qaitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prdname', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='actions',
            name='keeperapps',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actapps', to='common_core.keeperapps'),
        ),
        migrations.AddField(
            model_name='actions',
            name='actionprd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actprds', to='common_core.periods'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='catperiod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prds', to='common_core.periods'),
        ),
    ]
