# Generated by Django 5.2.9 on 2026-02-07 14:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_core', '0021_periods_alter_actions_keeperapps_actions_actionprd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='bookcost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='books',
            name='buydate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
