# Generated by Django 5.2.9 on 2026-02-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_core', '0022_books_bookcost_books_buydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='kind_of_book',
            field=models.CharField(choices=[('print', 'печатная'), ('digit', 'электронная')], default='print'),
        ),
    ]
