# Generated by Django 5.2.9 on 2026-02-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_core', '0023_alter_books_kind_of_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='is_verified',
            field=models.BooleanField(db_default=False),
        ),
    ]
