# Generated by Django 5.2.9 on 2026-02-07 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_core', '0024_books_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='pages',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='publ_year',
            field=models.IntegerField(null=True),
        ),
    ]
