# Generated by Django 5.2.9 on 2026-02-11 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_core', '0025_alter_books_pages_alter_books_publ_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=2)),
                ('usernick', models.CharField(max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='counts',
            name='owner_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owners', to='common_core.familyusers'),
        ),
    ]
