# Generated by Django 5.2.9 on 2026-02-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_core', '0026_familyusers_alter_counts_owner_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counts',
            name='owner_name',
            field=models.CharField(choices=[('S', 'СБ'), ('I', 'ИБ'), ('V', 'ВБ'), ('T', 'ТК')], default='S', max_length=5),
        ),
    ]
