# Generated by Django 5.2.9 on 2026-02-11 16:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_core', '0027_alter_counts_owner_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_num', models.IntegerField()),
                ('account_country', models.CharField(default='РФ', max_length=150)),
                ('account_type', models.CharField(choices=[('payment', 'расчетный'), ('card', 'дебетовая карта'), ('savings ', 'накопительный'), ('deposit', 'вклад/депозит'), ('broker', 'брокерский'), ('invest', 'инвестиционный'), ('depo', 'депозитарный'), ('credit', 'кредитный'), ('ndd', 'not dealing desk'), ('direct', 'direct')], default='card')),
                ('account_owner', models.CharField(choices=[('individual', 'Физическое лицо'), ('legal_entity', 'Юридическое лицо')], default='individual')),
                ('account_currency', models.CharField(choices=[('RUR', 'руб'), ('USD', 'долл сша'), ('EUR', 'евро'), ('USDT', 'крипто долл')], default='RUR')),
                ('account_curtype', models.CharField(choices=[('fiat', 'фиат'), ('cripto', 'крипто'), ('stocks', 'акции'), ('bonds', 'облигации'), ('objects', 'объекты')], default='fiat')),
                ('is_cardlinked', models.BooleanField(default=False)),
                ('account_sum', models.DecimalField(decimal_places=2, max_digits=15)),
                ('account_opendate', models.DateField(default=django.utils.timezone.now)),
                ('is_fnsknown', models.BooleanField(default=False)),
                ('account_coment', models.CharField(max_length=150, null=True)),
                ('account_finorg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='common_core.organizations')),
                ('owner_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owners', to='common_core.familyusers')),
            ],
        ),
        migrations.DeleteModel(
            name='Counts',
        ),
    ]
