# Generated by Django 5.2.9 on 2026-02-11 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_core', '0028_actives_delete_counts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivesType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activetype', models.CharField(max_length=50)),
            ],
        ),
    ]
