# Generated by Django 5.2.9 on 2026-02-12 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_core', '0029_activestype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familyusers',
            name='username',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='familyusers',
            name='usernick',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='queryanswers',
            name='appsname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projectapp', to='common_core.keeperapps'),
        ),
    ]
