# Generated by Django 5.2.9 on 2026-02-12 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_core', '0030_alter_familyusers_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActsCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actscategory', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ActSubCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actsubcategory', models.CharField(max_length=150)),
                ('actstatus', models.CharField(choices=[('online', 'онлайн'), ('offline', 'офлайн')], default='online')),
                ('addactdate', models.DateTimeField(auto_now_add=True)),
                ('actscategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actsub', to='common_core.actscategories')),
            ],
        ),
        migrations.DeleteModel(
            name='ActivesType',
        ),
        migrations.AlterField(
            model_name='categories',
            name='catbuhtype',
            field=models.CharField(choices=[('action', 'действие'), ('event', 'событие')], default='action'),
        ),
    ]
