# Generated by Django 5.2.9 on 2026-02-14 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_core', '0031_actscategories_actsubcategories_delete_activestype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='note_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notesapps', to='common_core.keeperapps'),
        ),
    ]
