# Generated by Django 5.2.9 on 2025-12-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyLibrary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=200)),
                ('tag_name', models.CharField(blank=True, max_length=50, null=True)),
                ('kind_of_book', models.CharField(blank=True, max_length=50, null=True)),
                ('author', models.CharField(max_length=100)),
                ('pages', models.PositiveIntegerField()),
                ('subject', models.CharField(max_length=100)),
                ('publ_seria', models.CharField(blank=True, max_length=100, null=True)),
                ('is_q_and_exc', models.BooleanField(default=False)),
                ('is_answers', models.BooleanField(default=False)),
                ('timestart', models.DateField(blank=True, null=True)),
                ('timefin_plan', models.DateField(blank=True, null=True)),
                ('timefin_fact', models.DateField(blank=True, null=True)),
                ('rating', models.IntegerField()),
                ('basic_thoughts', models.TextField(blank=True, null=True)),
                ('publ_year', models.IntegerField()),
                ('publ_house', models.CharField(max_length=100)),
                ('publ_city', models.CharField(blank=True, max_length=100, null=True)),
                ('coment', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'ordering': ['book_name'],
            },
        ),
    ]
