# Generated by Django 5.2.9 on 2026-02-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_hold', '0002_alter_familylibrary_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familylibrary',
            name='publ_house',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='familylibrary',
            name='rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='familylibrary',
            name='subject',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
