# Generated by Django 5.2.9 on 2026-02-07 10:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_core', '0021_periods_alter_actions_keeperapps_actions_actionprd_and_more'),
        ('house_hold', '0003_alter_familylibrary_publ_house_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionsFacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actstart', models.DateTimeField(auto_now_add=True)),
                ('actfinish', models.DateTimeField(default=django.utils.timezone.now)),
                ('actcoment', models.CharField(max_length=250, null=True)),
                ('actdone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actdone', to='common_core.actions')),
            ],
        ),
    ]
