# Generated by Django 5.2.9 on 2026-02-07 10:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_hold', '0004_actionsfacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionsfacts',
            name='actstart',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
