# Generated by Django 5.2.9 on 2026-02-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_hold', '0005_alter_actionsfacts_actstart'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionsfacts',
            name='actarea',
            field=models.CharField(choices=[('inside', 'в помещении'), ('inplace', 'в кровати/на кресле'), ('outside', 'на улице')], default='inside'),
        ),
        migrations.AddField(
            model_name='actionsfacts',
            name='actstatus',
            field=models.CharField(choices=[('online', 'онлайн'), ('offline', 'офлайн')], default='online'),
        ),
    ]
