# Generated by Django 5.2.9 on 2026-02-07 14:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_core', '0021_periods_alter_actions_keeperapps_actions_actionprd_and_more'),
        ('house_hold', '0006_actionsfacts_actarea_actionsfacts_actstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooksFacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestart', models.DateTimeField(default=django.utils.timezone.now)),
                ('timefin', models.DateTimeField(default=django.utils.timezone.now)),
                ('pagestart', models.PositiveIntegerField()),
                ('pagefin', models.PositiveIntegerField()),
                ('basic_thoughts', models.TextField(blank=True, null=True)),
                ('coment', models.CharField(blank=True, max_length=30, null=True)),
                ('book_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookdone', to='common_core.books')),
            ],
            options={
                'ordering': ['book_name'],
            },
        ),
        migrations.DeleteModel(
            name='FamilyLibrary',
        ),
    ]
