# Generated by Django 5.2.9 on 2026-02-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house_hold', '0007_booksfacts_delete_familylibrary'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksfacts',
            name='bookstatus',
            field=models.CharField(choices=[('in_progress', 'в работе'), ('on_delay', 'отложена'), ('read', 'прочитана')], default='inside'),
        ),
    ]
