# Generated by Django 5.2.9 on 2026-02-12 10:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_core', '0030_alter_familyusers_username_and_more'),
        ('house_hold', '0008_booksfacts_bookstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersActions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actstart', models.DateTimeField(default=django.utils.timezone.now)),
                ('actplandur', models.CharField(max_length=5)),
                ('actfactdur', models.CharField(max_length=5, null=True)),
                ('actstatus', models.CharField(choices=[('online', 'онлайн'), ('offline', 'офлайн')], default='online')),
                ('actarea', models.CharField(choices=[('inside', 'в помещении'), ('seatlace', 'на кресле'), ('bedlace', 'на диване'), ('outside', 'на улице')], default='inside')),
                ('actcoment', models.CharField(max_length=250, null=True)),
                ('actcat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actcat', to='common_core.categories')),
                ('actdone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actdone', to='common_core.subcategories')),
            ],
        ),
    ]
