# Generated by Django 5.2.9 on 2026-02-14 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_core', '0032_alter_notes_note_category'),
        ('house_hold', '0009_usersactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersactions',
            name='actdone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actdone', to='common_core.actsubcategories'),
        ),
    ]
